---
- name: Installing apached
  ansible.builtin.yum:
    name: "{{ apache_package }}"
    state: "{{ apache_package_state }}"

- name: Enable firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: yes
    state: started

- name: Start apached
  ansible.builtin.service:
    name: "{{ apache_service }}"
    enabled: "{{ apache_service_enabled }}"
    state: "{{ apache_service_state }}"

- name: Open apache ports
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp

- name: Create index
  ansible.builtin.copy:
    content: "Welcome to my web server"
    dest: /var/www/html/index.html
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '0644'
