---
- name: playbook2
  hosts: all

  tasks:
  - name: Stop httpd
    ansible.builtin.service:
      name: httpd
      state: stopped
      enabled: no

  - name: Uninstall httpd
    ansible.builtin.yum:
      name: httpd
      state: absent

  - name: Delete file
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: absent

  - name: Close ports
    ansible.posix.firewalld:
      service: http
      state: disabled
      permanent: yes

    

  